site_name: Daytistics
repo_name: daytistics/daytistics
repo_url: https://github.com/daytistics/daytistics

theme:
  name: material
  favicon: "assets/logo.png"
  font:
    code: Roboto markdown_extensions
  palette:
    - scheme: default
      primary: green
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: green
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.expand
    - search.highlight
    - dark_mode

nav:
  - Home: "index.md"
  - General:
      - Our Mission: "general/mission.md"
      - Features: "general/features.md"
  - Contributers Guide:
      - Overview: "contributers/overview.md"
      - Zen of Daytistics: "contributers/zen-of-daytistics.md"
      - Code of Conduct: "contributers/code-of-conduct.md"
      - Installation: "contributers/installation.md"
      - Services:
          - Core:
              - Overview: "contributers/services/core/overview.md"
              - API: "contributers/services/core/api.md"
              - Database: "contributers/services/core/database.md"
          - Modeler:
              - Overview: "contributers/services/modeler/overview.md"
              - API: "contributers/services/modeler/api.md"
          - Frontend:
              - Overview: "contributers/services/frontend/overview.md"
              - UI/UX: "contributers/services/frontend/ui-ux.md"
  - SaaS:
      - Overview: "saas/overview.md"
      - Hosting: "saas/hosting.md"

  # - Meeting Minutes:
  #    - Overview: "minutes/overview.md"

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite

extra_css:
  - "styles/extra.css"

extra_javascript:
  - "scripts/extra.js"
