name: License Check
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install license-header-checker
        run: curl -s https://raw.githubusercontent.com/lluissm/license-header-checker/master/install.sh | bash

      - name: Find and process files
        run: |
          find . -type f \( -name "*.py" -o -name "*.js" -o -name "*.html" -o -name "*.css" \) \
          ! -path "./node_modules/*" ! -path "./.venv/*" ! -path "./.pytest_cache/*" \
          -exec ./bin/license-header-checker -a -r ./LICENSE {} +
