name: Splitting services for deployment

on:
  push:
    branches:
      - dev
      - rest-with-spa

jobs:
  splitting-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Copy core to deploy-core branch
        run: |
          cd daytistics-core
          git fetch origin deploy-core || git checkout -b deploy-core
          git add .
          git commit -m "Copy core to deploy-core branch" || echo "No changes to commit"
          git push origin deploy-core
          cd ..

      - name: Copy frontend to deploy-frontend branch
        run: |
          cd daytistics-frontend
          git fetch origin deploy-frontend || git checkout -b deploy-frontend
          git add .
          git commit -m "Copy frontend to deploy-frontend branch" || echo "No changes to commit"
          git push origin deploy-frontend
          cd ..
